### ISSUE TITLE
Installation issue with pip 10

### ISSUE THREAD

**Issue by DavidMenting** [DigiThinkIT/erpnext_foxycart_integration#18]
Installing the app with pip 10 fails:
` ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/frappe/frappe-bench/apps/erpnext_foxycart_integration/setup.py", line 3, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
`

A fix is easy, as seen at https://stackoverflow.com/questions/25192794/no-module-named-pip-req . Changing the line to the following fixes the problem:

`try: # for pip >= 10
    from pip._internal.req import parse_requirements
except ImportError: # for pip <= 9.0.3
    from pip.req import parse_requirements`

I can create a pull request for this.

**Comment by Alchez** [comment]
Hey @DavidMenting, we actually are not maintaining this repo any longer, but feel free to make a PR :).
